Feature/sample
Appolica/TabControllerAndroid pull request #6
Opened 2017-03-25 10:40 UTC by bkolarov-appolica

2017-03-27 10:49 UTC, AlexanderI commented on TabController/sample/src/main/java/com/appolica/sample/tabs/NestedFragment.java
> +        binding.executePendingBindings();
There is no need to do executePendingBindings

2017-03-27 10:58 UTC, AlexanderI commented on TabController/sample/src/main/java/com/appolica/sample/tabs/pager/ViewPagerFragment.java
> +        binding.viewPager.setOffscreenPageLimit(1);
The default value is 1 anyway

2017-03-27 11:11 UTC, AlexanderI commented on TabController/sample/src/main/res/layout/fragment_stack_nested.xml
> +            android:layout_marginTop="8dp"
Just declare margin="8dp" will read better imo

2017-03-27 11:12 UTC, AlexanderI commented on TabController/sample/src/main/res/layout/fragment_tab_flat.xml
> +            android:layout_marginTop="8dp"
margin="8dp"

2017-03-27 11:13 UTC, AlexanderI commented on TabController/sample/src/main/res/layout/fragment_tab_view_pager.xml
> +            android:layout_marginTop="0dp"
margin="0dp"

2017-03-27 11:15 UTC, AlexanderI requested changes
Couple comments

2017-03-29 11:57 UTC, bkolarov-appolica commented on TabController/sample/src/main/res/layout/fragment_stack_nested.xml
> +            android:layout_marginTop="8dp"
layout_margin is ignored by the constraint layout editor.

2017-03-30 08:28 UTC, bkolarov-appolica commented
Necessary changes are made.

2017-03-30 08:38 UTC, AlexanderI approved these changes

2017-03-30 08:38 UTC, merged